name: Auto labels

on:
  workflow_dispatch:
  push:
    paths:
      - ".autorc.json"

jobs:
  create:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: auto-it/setup-auto@v1

      - name: Create Labels
        run: auto create-labels